services:
  mysql:
    image: mysql:latest
    container_name: khmerjava-api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: khmerjava-db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - khmerjava-api-db-data:/var/lib/mysql

volumes:
  khmerjava-api-db-data:
